"""Ajust relationship in models

Revision ID: 72e3a0287ef5
Revises: 
Create Date: 2024-10-05 22:10:23.145600

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "72e3a0287ef5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
